version: '3.7'
services:

  mysql:
    image: mysql:5.7.26
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tracker_test
      - MYSQL_USER=tracker
      - MYSQL_PASSWORD=tracker
      - MYSQL_ALLOW_EMPTY_PASSWORD
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s
